#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <shadow.h>
#include <sys/types.h>
#include <pwd.h>
#define _XOPEN_SOURCE
#include <unistd.h>
#include <sys/socket.h>
#include <sys/wait.h>
#include <errno.h>
#include <netinet/in.h>
#include <netdb.h>
#include <string.h>
#define __USE_XOPEN
#include <arpa/inet.h>
#include <time.h>
#include <syslog.h>
#include <signal.h>
#include <sys/stat.h>
#include <math.h>
#include <crypt.h>
#include <ctype.h>
